### ISSUE TITLE
Recommend changing the font to Estedad to a better Kurdish Support

### ISSUE THREAD

**Issue by dolanskurd** [roj1512/xera#6]
It seems Vazir is not the latest updated one that used here. So try to use the latest version from here (https://rastikerdar.github.io/vazir-font/) or use Estedad (https://aminabedi68.github.io/Estedad/) which has better support for Kurdish.

The issue example:
![image](https://user-images.githubusercontent.com/18519747/151312751-6dad8c69-0086-4ee6-aaab-24d212d3da5e.png)

**Comment by roj1512** [comment]
![image](https://user-images.githubusercontent.com/49933115/151342124-2cfd9ef2-a9fa-4691-a0ad-b3e14df03c6d.png)
I tried to use Estedad, but I have this bizwên problem.

**Comment by roj1512** [comment]
This was unexpectedly closed.

**Comment by dolanskurd** [comment]
Estedad font covered almost all the Kurdish issues. I have no Idea what happened to your case. Just keep it in mind not to use the variable formats (for now). As far as I checked, they are not supported correctly by the explorers.

**Comment by roj1512** [comment]
How do you import it?

**Comment by dolanskurd** [comment]
> How do you import it?

I didn't test it here! I have tested before in some other projects and the issue was from the variable fonts. Check it out and try to use the normal fonts. Probably the issue will be sorted out then.

**Comment by roj1512** [comment]
@dolanskurd do me one favor, tell me if the Vazir problem still persists

**Comment by dolanskurd** [comment]
> @dolanskurd do me one favor, tell me if the Vazir problem still persists 

Everything is working fine. Thank you.

**Comment by roj1512** [comment]
Cool! I will close this when I have made Estedad work, because really I like it.
